### ISSUE TITLE
cp: bad substitution

### ISSUE THREAD

**Issue by bao3** [jeantil/autokbisw#15] opened 2017-12-19 10:25 UTC
```

bash-3.2$ cp ${le chemin ci-dessus} /usr/local/bin/
bash: ${le chemin ci-dessus}: bad substitution
```

```
pwd
```
>[.....]/Users/jean/dev/opt/autokbis

```
ll
```

>total 10676
>-rwxr-xr-x 1 bao3 10929376 Dec 19 18:16 autokbisw

How to resolve it ?

**Comment by jeantil** [comment] 2017-12-19 21:48
Hi, 

thanks for submitting your issue.
I have improved the instructions in the readme to try to address your issue. 
Could you try following the new ones ?

**Comment by bao3** [comment] 2017-12-20 06:44
@jeantil  Thank you for your warm reply , another issue  while I built in xcode was `2017-12-20 14:42:25.655393+0800 autokbisw[48251:581615] Month 13 is out of bounds`

**Comment by jeantil** [comment] 2017-12-20 15:39
hmm I have never had this issue ... can you paste a full build log ? I don't think I do any time manipulation in my build or project...

**Comment by jeantil** [comment] 2019-02-26 11:50
I'll close this for now as I can't reproduce and the build system changed a bit since you opened the issue (including a brew recipe). 
Don't hesitate to comment further if you feel the issue should still be adressed

**Closed by jeantil** 2019-02-26 11:50 UTC
